service: sls-dynamodb-ttl-and-stream-test1

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  timeout: 30
  logRetentionInDays: 1 # Set the default RetentionInDays for a CloudWatch LogGroup
  deploymentBucket:
    name: labs-lambda-deployments
  environment:
    STAGE: ${self:provider.stage}
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
    DYNAMODB_REGION: "eu-west-1"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        # New permissions needed for stream
        - dynamodb:GetRecords
        - dynamodb:GetShardIterator
        - dynamodb:DescribeStream
        - dynamodb:ListStreams
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

resources:
  Resources:
    SlsDynamodbTtlAndStreamTest1:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        StreamSpecification:
          StreamViewType: OLD_IMAGE
        TimeToLiveSpecification:
          AttributeName: expireAt
          Enabled: true
        TableName: ${self:provider.environment.DYNAMODB_TABLE}

functions:
  insert-into-dynamodb:
    handler: src/handler.insert
    events:
      - http:
          path: test
          method: get
          cors: true
  
  handleSteam:
      handler: src/handler.steamTrigger
      events:
        - stream:
            type: dynamodb
            arn: { Fn::GetAtt: [ SlsDynamodbTtlAndStreamTest1, StreamArn ] }
            # arn: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
            # Fn::GetAtt:
            #   - expirationsTable
            #   - StreamArn

